# Generated by Django 2.2.10 on 2020-05-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0002_user_is_developer_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_developer_admin',
            field=models.BooleanField(default=False),
        ),
    ]
