# Generated by Django 2.2.10 on 2022-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0005_user_is_developer_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_employee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
