# Generated by Django 2.2.10 on 2022-10-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0006_user_linked_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
