# Generated by Django 2.2.10 on 2022-10-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditapp', '0007_user_is_main_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_main_client',
            field=models.BooleanField(default=False),
        ),
    ]
