# Generated by Django 2.2.10 on 2022-11-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaxFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_client', models.CharField(blank=True, max_length=20, null=True)),
                ('max_files', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'maxfiles',
            },
        ),
        migrations.CreateModel(
            name='MaxUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_client', models.CharField(blank=True, max_length=20, null=True)),
                ('max_users', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'maxusers',
            },
        ),
    ]
