# Generated by Django 2.2.10 on 2022-11-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0002_maxfiles_current_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxusers',
            name='current_users',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
