# Generated by Django 4.1.4 on 2023-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0003_maxusers_current_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_client', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_generation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('current_date', models.DateField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'billingdetails',
            },
        ),
    ]
