# Generated by Django 4.1.4 on 2023-01-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0004_billingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('count', models.CharField(default=0, max_length=100)),
            ],
            options={
                'db_table': 'userfilecount',
            },
        ),
    ]
