# Generated by Django 4.1.4 on 2023-01-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0005_userfilecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingDetails',
        ),
    ]
