# Generated by Django 4.1.4 on 2023-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0006_delete_billingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_client', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_generation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('current_date', models.DateField(auto_now=True)),
                ('transactionID', models.CharField(max_length=100)),
                ('paymentmode', models.CharField(default='Online', max_length=20)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'billingdetails',
            },
        ),
    ]
