# Generated by Django 4.1.4 on 2023-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0007_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='account_type',
            field=models.CharField(default='Trial', max_length=20),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
