# Generated by Django 4.1.4 on 2023-01-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0008_billingdetails_account_type_billingdetails_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='current_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='start_date',
            field=models.DateField(),
        ),
    ]
