# Generated by Django 4.1.4 on 2023-01-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_client', '0009_alter_billingdetails_current_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainclient_identifier', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('txnid', models.CharField(max_length=100)),
                ('productinfo', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('surl', models.CharField(max_length=100)),
                ('furl', models.CharField(max_length=100)),
                ('hash', models.CharField(max_length=500)),
                ('main_client', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('used', models.CharField(blank=True, default='no', max_length=20, null=True)),
                ('archived', models.CharField(blank=True, default='no', max_length=20, null=True)),
            ],
            options={
                'db_table': 'billingtransaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=50)),
                ('mihpayid', models.CharField(blank=True, max_length=50, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('unmappedstatus', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.CharField(blank=True, max_length=50, null=True)),
                ('txnid', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('cardCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('net_amount_debit', models.CharField(blank=True, max_length=50, null=True)),
                ('addedon', models.CharField(blank=True, max_length=50, null=True)),
                ('productinfo', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_source', models.CharField(blank=True, max_length=50, null=True)),
                ('PG_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=50, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=50, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=50, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'transactiondetails',
            },
        ),
    ]
