# Generated by Django 2.2.10 on 2020-05-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_firm_name', models.CharField(max_length=255)),
                ('ca_firm_registration_id', models.CharField(max_length=255)),
                ('ca_firm_address', models.CharField(max_length=255)),
                ('ca_firm_pan', models.CharField(max_length=255)),
                ('ca_firm_tan', models.CharField(max_length=255)),
            ],
        ),
    ]
