# Generated by Django 2.2.10 on 2020-06-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_description', models.CharField(default='', max_length=255)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='partner.Act')),
            ],
        ),
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('pan_no', models.CharField(default='', max_length=255)),
                ('tan_no', models.CharField(default='', max_length=255)),
                ('gst_no', models.CharField(default='', max_length=255)),
                ('is_audit_plan_locked', models.BooleanField(default=False)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulator_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_estimated_days', models.CharField(blank=True, max_length=255, null=True)),
                ('task_auditing_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('task_international_auditing_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='partner.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_estimated_days', models.CharField(blank=True, max_length=255, null=True)),
                ('task_auditing_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('task_international_auditing_standard', models.CharField(blank=True, max_length=255, null=True)),
                ('task_start_date', models.DateField(blank=True, null=True)),
                ('task_end_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='task_submission/')),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_start', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('rejection_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('reject_task_remark', models.CharField(blank=True, max_length=255, null=True)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Act')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_task', to='partner.Activity')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='regulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Regulator'),
        ),
    ]
