# Generated by Django 2.2.10 on 2020-06-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20200615_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAuditTypeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Activity')),
                ('audittype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.AuditType')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Entity')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Industry')),
            ],
        ),
    ]
