# Generated by Django 2.2.10 on 2020-06-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_clientindustryaudittypeentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='regulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Regulator'),
        ),
    ]
