# Generated by Django 2.2.10 on 2020-06-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_clienttask_regulator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_name', models.CharField(max_length=255)),
            ],
        ),
    ]
