# Generated by Django 2.2.10 on 2020-06-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_audits'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulator',
            name='type_of_audits',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
