# Generated by Django 2.2.10 on 2020-08-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20200705_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='regulator',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='clienttask',
            old_name='regulator',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='regulator',
            old_name='regulator_name',
            new_name='area_name',
        ),
    ]
