# Generated by Django 2.2.10 on 2020-09-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_clienttask_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPlanMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditplanname', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('finance_year', models.CharField(max_length=255)),
                ('is_audit_plan_locked', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Client')),
            ],
        ),
    ]
