# Generated by Django 2.2.10 on 2020-09-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_auditplanmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='auditplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.AuditPlanMapping'),
        ),
    ]
