# Generated by Django 2.2.10 on 2020-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_clienttask_auditplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplanmapping',
            name='auditplan_frequency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='finance_year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
