# Generated by Django 2.2.10 on 2020-09-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_auto_20200909_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttask',
            name='area',
        ),
        migrations.RemoveField(
            model_name='clienttask',
            name='task',
        ),
    ]
