# Generated by Django 2.2.10 on 2020-09-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_auto_20200911_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplanmapping',
            name='audittype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.AuditType'),
        ),
    ]
