# Generated by Django 2.2.10 on 2020-12-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0018_auditplanmapping_audittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='task_relevance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='task_sample_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='task_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
