# Generated by Django 2.2.10 on 2020-12-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0019_auto_20201212_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttask',
            name='task_relevance',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='task_sample_rate',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='task_volume',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
