# Generated by Django 2.2.10 on 2021-01-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_auto_20201212_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='manager_attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submission/'),
        ),
    ]
