# Generated by Django 2.2.10 on 2021-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0021_clienttask_manager_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='manager_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='task_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
