# Generated by Django 2.2.10 on 2021-01-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0023_task_process_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='process_notes',
            field=models.FileField(blank=True, null=True, upload_to='activity_process_notes/'),
        ),
    ]
