# Generated by Django 2.2.10 on 2021-02-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0024_activity_process_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='partner_attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submission/'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='partner_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
