# Generated by Django 2.2.10 on 2021-02-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0025_auto_20210202_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='partner_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
