# Generated by Django 2.2.10 on 2021-06-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0028_clienttask_is_approved_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=1024),
        ),
    ]
