# Generated by Django 2.2.10 on 2021-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0029_auto_20210602_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_audit_plan_locked',
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='invoice_amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='invoice_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
