# Generated by Django 2.2.10 on 2021-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0030_auto_20210604_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplanmapping',
            name='out_of_pocket_expenses',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
