# Generated by Django 2.2.10 on 2021-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0032_auditplanmapping_is_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplanmapping',
            name='cgst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='igst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='sgst',
            field=models.FloatField(null=True),
        ),
    ]
