# Generated by Django 2.2.10 on 2021-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0033_auto_20210619_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplanmapping',
            name='cgst_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='igst_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='sgst_amount',
            field=models.FloatField(null=True),
        ),
    ]
