# Generated by Django 2.2.10 on 2021-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0035_auditplanmapping_out_of_pocket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditplanmapping',
            name='out_of_pocket',
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='ope_gst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='total_ope',
            field=models.FloatField(null=True),
        ),
    ]
