# Generated by Django 2.2.10 on 2021-06-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0036_auto_20210622_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditplanmapping',
            name='ope_gst',
        ),
        migrations.RemoveField(
            model_name='auditplanmapping',
            name='total_ope',
        ),
    ]
