# Generated by Django 2.2.10 on 2021-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0037_auto_20210622_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplanmapping',
            name='ope_gst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='total_ope',
            field=models.FloatField(null=True),
        ),
    ]
