# Generated by Django 2.2.10 on 2021-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0038_auto_20210622_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditplanmapping',
            old_name='ope_gst',
            new_name='ope_cgst',
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='ope_igst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='auditplanmapping',
            name='ope_sgst',
            field=models.FloatField(null=True),
        ),
    ]
