# Generated by Django 2.2.10 on 2021-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0040_auto_20210913_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplanmapping',
            name='actual_end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='estimated_end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='invoice_amount',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='invoice_amount_paid',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='invoice_paid_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
