# Generated by Django 2.2.10 on 2021-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0041_auto_20210914_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplanmapping',
            name='cgst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='cgst_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='igst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='igst_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='ope_cgst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='ope_igst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='ope_sgst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='out_of_pocket_expenses',
            field=models.CharField(default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='sgst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='sgst_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='total_ope',
            field=models.FloatField(default=0, null=True),
        ),
    ]
