# Generated by Django 4.0.6 on 2022-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0043_auto_20210917_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='finance_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
