# Generated by Django 2.2.10 on 2022-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0044_client_client_email_client_finance_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(blank=True, max_length=20, null=True)),
                ('employee', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'userlink',
            },
        ),
    ]
