# Generated by Django 4.1.4 on 2023-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0045_userlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='article_attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submission/'),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='auditor_attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='task_submission/'),
        ),
    ]
