# Generated by Django 4.1.4 on 2023-01-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0046_clienttask_article_attachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='task_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='task_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
