# Generated by Django 4.1.4 on 2023-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0048_alter_clienttask_article_attachment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttask',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
