# Generated by Django 4.1.4 on 2023-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0051_audittype_user_entity_user_industry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
