# Generated by Django 4.1.4 on 2023-02-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0052_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='user_id',
        ),
    ]
