# Generated by Django 4.1.4 on 2023-02-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0053_rename_user_client_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplanmapping',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanmapping',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
