# Generated by Django 4.1.4 on 2023-02-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0054_alter_auditplanmapping_actual_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulator',
            name='type_of_audits',
            field=models.CharField(max_length=20),
        ),
    ]
