# Generated by Django 4.1.4 on 2023-02-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0056_activity_is_global_activity_labels_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
