# Generated by Django 4.1.4 on 2023-02-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0060_alter_task_process_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttask',
            name='attachment_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='task_submission/'),
        ),
    ]
