# Generated by Django 4.1.4 on 2023-03-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0061_alter_clienttask_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttask',
            name='article_attachment_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='auditor_attachment_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='manager_attachment_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='partner_attachment_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
