# Generated by Django 4.1.4 on 2023-03-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0062_alter_clienttask_article_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='process_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='process_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
